"""Core domain models for Agent Kernel."""

from agent_kernel.domain.agent import AgentSession, AgentSpec, AgentTaskResult, MailboxMessage, MailboxMessageStatus
from agent_kernel.domain.autonomy import (
  AcceptanceCriteria,
  AttemptStatus,
  CandidateStrategy,
  ExplorationAttempt,
  ExplorationStatus,
  ExplorationTask,
  GoldenTrace,
  ReflectionRecord,
  ReflectionStatus,
  SkillEvolutionRecord,
  WorkflowTemplate,
  WorkflowTemplateStatus,
)
from agent_kernel.domain.capability import CapabilityGrant, CapabilitySpec, ToolResult
from agent_kernel.domain.context import ContextCandidate, ContextPlan, ModelContext, RetrievalPack
from agent_kernel.domain.conversation import Message, Objective, Thread
from agent_kernel.domain.events import RuntimeEvent, RuntimeEventType
from agent_kernel.domain.extension import ExtensionContribution, ExtensionManifest
from agent_kernel.domain.identifiers import ArtifactRef, EntityRef, MemoryRef
from agent_kernel.domain.interaction import (
  AgentPool,
  ChannelMode,
  DiscussionTurn,
  GroupChatSession,
  HandoffRecord,
  InteractionChannel,
  InteractionMessage,
  InteractionParticipant,
  ObservationFinding,
  ParticipantKind,
  PatchArtifact,
  ReviewRecord,
  SpeakerPolicy,
  SpeakerPolicyType,
  TaskBoardItem,
  WorkspaceLease,
)
from agent_kernel.domain.memory import MemoryItem
from agent_kernel.domain.policy import ApprovalRequest, HumanIntervention, RuntimeControlRequest
from agent_kernel.domain.run import RunState
from agent_kernel.domain.skill import (
  PlanPatch,
  PlanPatchStatus,
  SkillCard,
  SkillExecutionMode,
  SkillStatus,
  SkillUsePolicy,
)
from agent_kernel.domain.stability import (
  CircuitBreakerState,
  DeadLetterItem,
  RecoveryJob,
  RuntimeBudget,
)
from agent_kernel.domain.states import (
  AgentStatus,
  ApprovalStatus,
  CircuitStatus,
  HumanInterventionStatus,
  NodeStepStatus,
  RecoveryStatus,
  RunStatus,
  TaskStatus,
  ToolCallStatus,
  assert_transition,
  can_transition,
)
from agent_kernel.domain.step import NodeStepRecord
from agent_kernel.domain.task import Task, TaskClaim
from agent_kernel.domain.tool_call import ToolCallRecord
from agent_kernel.domain.workflow import (
  EdgeSpec,
  ExecutionCommand,
  NodeContext,
  NodeResult,
  NodeSpec,
  WorkflowSpec,
)

__all__ = [
  "AgentSession",
  "AgentSpec",
  "AgentStatus",
  "AgentPool",
  "AgentTaskResult",
  "AcceptanceCriteria",
  "ApprovalRequest",
  "ApprovalStatus",
  "ArtifactRef",
  "AttemptStatus",
  "CapabilityGrant",
  "CapabilitySpec",
  "CandidateStrategy",
  "ChannelMode",
  "CircuitBreakerState",
  "CircuitStatus",
  "ContextCandidate",
  "ContextPlan",
  "DeadLetterItem",
  "DiscussionTurn",
  "EdgeSpec",
  "EntityRef",
  "ExecutionCommand",
  "ExplorationAttempt",
  "ExplorationStatus",
  "ExplorationTask",
  "ExtensionContribution",
  "ExtensionManifest",
  "GoldenTrace",
  "GroupChatSession",
  "HandoffRecord",
  "HumanIntervention",
  "HumanInterventionStatus",
  "InteractionChannel",
  "InteractionMessage",
  "InteractionParticipant",
  "MemoryItem",
  "MemoryRef",
  "Message",
  "MailboxMessage",
  "MailboxMessageStatus",
  "ModelContext",
  "NodeContext",
  "NodeResult",
  "NodeSpec",
  "NodeStepRecord",
  "NodeStepStatus",
  "Objective",
  "ObservationFinding",
  "ParticipantKind",
  "PatchArtifact",
  "SpeakerPolicy",
  "SpeakerPolicyType",
  "PlanPatch",
  "PlanPatchStatus",
  "ReviewRecord",
  "RecoveryJob",
  "RecoveryStatus",
  "ReflectionRecord",
  "ReflectionStatus",
  "RetrievalPack",
  "RunState",
  "RunStatus",
  "RuntimeBudget",
  "RuntimeControlRequest",
  "RuntimeEvent",
  "RuntimeEventType",
  "SkillCard",
  "SkillExecutionMode",
  "SkillEvolutionRecord",
  "SkillStatus",
  "SkillUsePolicy",
  "Task",
  "TaskBoardItem",
  "TaskClaim",
  "TaskStatus",
  "Thread",
  "ToolCallStatus",
  "ToolCallRecord",
  "ToolResult",
  "WorkflowSpec",
  "WorkflowTemplate",
  "WorkflowTemplateStatus",
  "WorkspaceLease",
  "assert_transition",
  "can_transition",
]
