"""Capability adapter implementations."""

from agent_kernel.capabilities.adapters.control import (
  ADBMobileBackend,
  CommandResult,
  ControlBackend,
  ControlCommand,
  ControlResult,
  ControlTarget,
  ControlWorkbench,
  DesktopUIDetector,
  FakeControlBackend,
  TMWebDriverHTTPBackend,
  UIAStyleDesktopDetector,
  Win32DesktopBackend,
)
from agent_kernel.capabilities.adapters.local import LocalToolExecutor
from agent_kernel.capabilities.adapters.mcp import (
  FakeMCPClient,
  MCPClient,
  MCPServerCommand,
  MCPToolBinding,
  MCPToolExecutor,
  StdioMCPClient,
)
from agent_kernel.capabilities.adapters.process import (
  PosixProcessGroupIsolationStrategy,
  ProcessCommand,
  ProcessIsolationStrategy,
  ProcessStreamEvent,
  ProcessToolExecutor,
  SingleProcessIsolationStrategy,
)
from agent_kernel.capabilities.adapters.workbench import (
  FakeWorkbenchClient,
  HTTPWorkbenchClient,
  HTTPWorkbenchEndpoint,
  WorkbenchClient,
  WorkbenchCommand,
  WorkbenchResult,
)

__all__ = [
  "ADBMobileBackend",
  "CommandResult",
  "ControlBackend",
  "ControlCommand",
  "ControlResult",
  "ControlTarget",
  "ControlWorkbench",
  "DesktopUIDetector",
  "FakeMCPClient",
  "FakeControlBackend",
  "FakeWorkbenchClient",
  "HTTPWorkbenchClient",
  "HTTPWorkbenchEndpoint",
  "LocalToolExecutor",
  "MCPClient",
  "MCPServerCommand",
  "MCPToolBinding",
  "MCPToolExecutor",
  "PosixProcessGroupIsolationStrategy",
  "ProcessCommand",
  "ProcessIsolationStrategy",
  "ProcessStreamEvent",
  "ProcessToolExecutor",
  "SingleProcessIsolationStrategy",
  "StdioMCPClient",
  "TMWebDriverHTTPBackend",
  "UIAStyleDesktopDetector",
  "Win32DesktopBackend",
  "WorkbenchClient",
  "WorkbenchCommand",
  "WorkbenchResult",
]
